# This is a default site configuration which will simply return 404, preventing
# chance access to any other virtualhost.

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name pablo.42.fr; # Tu login de 42

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;

	root /var/www/html;
	index index.php index.html;

	location / {
        	try_files $uri $uri/ =404;
	}

    # Conexión con el contenedor WordPress
	location ~ \.php$ {
		include fastcgi_params;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass wordpress:9000; # Nombre del servicio en tu docker-compose
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}
}
